### Check status
GET http://127.0.0.1:5000/

### Get RSS
GET http://127.0.0.1:5000/get-rss
?rss-url={{TestAddress}}

### Get RSS List
GET http://127.0.0.1:5000/rss

### Get RSS By Id
GET http://127.0.0.1:5000/rss
?id=1

### Add to RSS List
POST http://127.0.0.1:5000/rss
Content-Type: application/json

{
    "rss-url":"{{TestAddress}}",
    "title":"{{TestTitle}}",
    "description":"{{TestDescription}}"
}

### update RSS
PATCH http://127.0.0.1:5000/rss
Content-Type: application/json

{
    "id": 1,
    "rss-url":"{{TestAddress}}",
    "title":"{{TestTitle}}",
    "description":"{{TestDescription}}"
}

### Delete from RSS List
DELETE http://127.0.0.1:5000/rss
?id=1